### ISSUE TITLE
Moving viewport to cursor location

### ISSUE THREAD

**Issue by reagle** [vsc-cnst/SublimeTextFileFilter#3]
Thank you for this package, neat! I've long used [Filter Lines](https://packagecontrol.io/packages/Filter%20Lines) and your plugin doesn't create a new tab/file, rather it folds. This is advantageous for navigating to or editing text in the actual file. Some thoughts:

1. If I place my cursor on a line in the folded view, when I hit escape the viewport shows the top of the file, rather than the line with the cursor in it. I can always move the viewport by hitting the left or right arrow (or `super+k,super+c`), but perhaps on escape it could `show_at_center`.
2. I like that if I unfold-all, instead of escape, the highlights remain.
3. A possible downside is that when I escape or unfold, and previous foldings I had have been lost.

**Comment by vsc-cnst** [comment]
Hi,

thank you for the positive feedback and for taking the time to suggest improvements!

#### Regarding nr 1
if I understand correctly, repro steps would be:
1. Filter file
2. Expand a folder region
3. It escape to unfold a
4. NOT OK: Carrer is moved to the beginning of the file
-Expected result : Carrer is in the same position as before clearing the filter

#### Regarding nr 2

Escape key is purposely meant to clear all and exit the filter file extension - providing an easy and intuitive way to exit.

There is a command for unfolding all. This is meant to unfold all but maintaining the highlights. I’ll add a feature to make it possible to configure keyboard shortcuts for each of folding styles (e.g. `ctrl+foo,ctrl+bar`). This way, you can set a shortcut for unfold all file without removing the highlights.

Let me know if this will work for you.


Once again, thanks for your feedback.

**Comment by reagle** [comment]
> NOT OK: Carrer is moved to the beginning of the file

My issue is not with the cursor. It's that when I escape, the viewport is at the top of the file, rather than where the cursor is. In this clip, the cursor is on line 100, I invoke your filter for all "log\." lines, move the cursor to line 261, escape, and my viewport is at the top of the document instead on line 261. Moving the cursor left/right restores the viewport to line 261, but the viewport should automatically be on the cursor location (i.e., `show_at_center`).

[file-filter-shot.webm](https://github.com/user-attachments/assets/e061ba64-bb44-4089-968e-458f75715e20)

> Regarding nr 2

Sorry for not being clear. Imagine I have already folded some of my functions. Then I use your plugin, escape, and now everything is unfolded, which annoys me because I wanted my earlier folds functions to remain folded. I don't know if it's possible (or worth it really) to save the existing folds and _restore_ those on escaping the filter view/fold.

**Comment by vsc-cnst** [comment]
HI,

I've release a new version (2.1.0) where you will be able to configure what happens after clear command runs.

default options are

`
 {
    "on_clear_command_options":{
        "unfold_regions": true,
        "remove_highlights": true,
        "center_viewport_on_carret": true
    }
}
`
you can override them as you need.

Hope this meets your expectations.

**Comment by reagle** [comment]
Excellent! Thank you.
