### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by reagle** [vsc-cnst/SublimeTextFileFilter#5]
How do I do case insensitive searches?

**Comment by vsc-cnst** [comment]
Hi,

You can use the `(?aiLmsux-imsx:...)` syntax to add flags.

Example:
- using `(?:PYTHON)` as regex, filter will match lines with both `python` and `PYTHON` 
- using `(?:PYTHON)outter` as regex, filter will match lines with both `pythonoutter` and `PYTHONoutter` 

As this is a python plug, you can follow [python regex docs](https://docs.python.org/3/library/re.html#regular-expression-syntax) for detailed information.

**Comment by reagle** [comment]
You might want to include this on the README: I didn't know if I should use PCRE (which ST uses) or python flags. It'd also be nice to have a setting so I can set the default as insensitive.

**Comment by vsc-cnst** [comment]
It is already on the README
I'll put in backlog a setting for global flgas

**Comment by reagle** [comment]
Sorry, I meant right at the start:

> This plugin allows you to filter file content using **Python** regular expressions (RegExp) — it does not change the file content.
> ...
> ## Features
> - File Filtering using Python RegExp
